-- Q4 What is the total Monthly Recurring Revenue (MRR)
-- generated by each subscription plan?

SELECT
    p.plan_name,
    SUM(s.mrr) AS total_mrr
FROM subscriptions s
JOIN plans p
    ON s.plan_id = p.plan_id
GROUP BY p.plan_name
ORDER BY total_mrr DESC;